### ISSUE TITLE
Unable to add a new event to the homepage

### ISSUE THREAD

**Issue by geospatialem** [maptime/msp#11]
Hey @maptime/us-mn-msp,

I've been attempting to add a new event to the site and keep hitting brick walls, can anyone find out why the **[March event](https://github.com/maptime/msp/blob/gh-pages/_posts/2016-03-17-March-Projects.md)** won't load into the homepage properly?

Thank you in advance,
:smirk_cat:

**Comment by fawcett** [comment]
Kitty, 
This is a weird one.  I compared the markdown from this post with the January post, and it is essentially the same.  

I ended up adding an author line to March to match January, and I changed the title, but that didn't seem to make a difference.  Still no render.  The map link in the iframe tags is good too.
Are you still editing code in MS Word? @geospatialem ...

Any ideas @geobrando?

**Comment by geospatialem** [comment]
Thanks for checking, @fawcett! I'm wondering if its related  to one of the template changes I made last year? Although other posts were coming in okay after I made the changes, so who knows:question:

I do all my editing in the [Atom editor](http://atom.io), but thought it could be related to some cosmetics ("@", "*", "-", etc.), thus all the commits, but no :game_die: .

**Comment by geografa** [comment]
Maybe try fiddling with the file name and change it to the past and see if it works. We were having similar issues so wondering if there's an issue with Jekyll that would be upstream.

**Comment by geospatialem** [comment]
@geografa Weird, so changing the date to `2015` works, it appears on the page, but changing it back to `2016` seems to be the issue.

**Comment by geografa** [comment]
@geospatialem hmm. l can get this working on our repo (/portland) but not seeing any differences between our layouts. Are you saying you're seeing this in production only? Or is this happen when you test it locally as well?

**Comment by mtaylorlong** [comment]
Hey y'all! I believe I ran into this same issue on the milehigh site a few weeks ago. @emilyashley solved our problem in [this issue](https://github.com/maptime/maptime-admin/issues/176) by adding “future:true” to our _config.yml. Could that be the solution to this your issue as well?

**Comment by geografa** [comment]
@mtaylorlong that's totally the issue! Thank you!

**Comment by geospatialem** [comment]
@mtaylorlong @geografa @fawcett @emilyashley you all :guitar:!! Thank you all so much!

HOORAY!!!! :fireworks: :confetti_ball: :tada: :sparkler:
