### ISSUE TITLE
Add url to repo?

### ISSUE THREAD

**Issue by geospatialem** [maptime/msp#9]
Can we add the website url to the [repo](https://github.com/maptime/msp)? It doesn't look like I have rights to add it in. The URL is: http://maptime.io/msp.

Thank you in advance, :guitar::star2:'s!

-:smile_cat:

**Comment by fawcett** [comment]
Done.  

We should get you commit privs for the repo too.

**Comment by geobrando** [comment]
Hey @geospatialem .  Weird. According to the settings, you're a member of the `us-mn-msp` team and have write privileges to the msp repo.

**Comment by geospatialem** [comment]
Hey @geobrando, I believe I have the proper rights to edit the repo. 

The 'reasoning behind the madness' with this issue was with the URL, which I'm guessing requires additional permissions? I don't necessarily need additional permissions though. 

**Could you add in the url similar to [Portland](https://github.com/maptime/portland)'s like so:**

![shotofscreen](https://cloud.githubusercontent.com/assets/5023024/10883087/43a7478a-8135-11e5-9bdc-f9c1505d7ea6.png)

Our url is: http://maptime.io/msp

Thank you for responding so quickly!

**Comment by fawcett** [comment]
Now I see where you are talking about Kitty.  On repo's that I own, I get a form to enter the description and URL for  a repo.  With Github org accounts, it seems like we don't get that priv as a normal collaborator.

**Comment by geobrando** [comment]
Hi there. Yes, I believe that with our settings only owners are allowed to make this change.  It's now added.

**Comment by geospatialem** [comment]
Awesome, thank you, @geobrando!!! :+1:
